In [45]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np

In [164]:
row_data = pd.read_csv('./1961_to_1962.csv')

In [4]:
row_data = pd.read_csv('./1961_')

Unnamed: 0  Unnamed: 0.1             bs             id  \
count  1.865520e+05  1.865520e+05  186552.000000  186552.000000   
mean   4.531631e+06  4.531632e+06       4.847687    1419.936114   
std    1.803631e+06  1.803631e+06       0.946211     553.248182   
min    2.653610e+05  2.653620e+05       0.693147      82.000000   
25%    3.845601e+06  3.845602e+06       4.234107    1234.000000   
50%    4.746020e+06  4.746022e+06       4.844187    1514.000000   
75%    6.133006e+06  6.133007e+06       5.455321    1901.000000   
max    8.977115e+06  8.977116e+06       8.958540    2714.000000   

                 day           year           yday           wday  \
count  186552.000000  186552.000000  186552.000000  186552.000000   
mean      466.023811    1962.519914     186.255194       3.994329   
std       209.072081       0.499605     105.500851       1.984648   
min        91.000000    1962.000000       1.000000       1.000000   
25%       289.000000    1962.000000      94.000000       2.000000   
50%       470.000000    1963.000000     188.000000       4.000000   
75%       647.000000    1963.000000     278.000000       6.000000   
max       820.000000    1963.000000     365.000000       7.000000   

               Tmin0         Tmean1         Tmean2          Tmax0  \
count  186552.000000  186552.000000  186552.000000  186552.000000   
mean        4.677932       8.001729       7.996374      11.350031   
std         5.305613       5.479733       5.488111       6.022369   
min       -18.000000     -11.000000     -11.000000      -6.500000   
25%         1.000000       4.000000       4.000000       7.000000   
50%         5.500000       9.000000       9.000000      12.000000   
75%         9.000000      12.500000      12.500000      16.000000   
max        16.000000      21.000000      21.000000      27.500000   

            rainfall              x              y              h  \
count  186552.000000  186552.000000  186552.000000  186552.000000   
mean       64.535406     394.390423     398.781226      94.121559   
std        36.971678      33.375232      29.615283      61.450119   
min         2.000000     300.500000     300.200000       4.000000   
25%        37.000000     371.600000     388.800000      40.000000   
50%        60.000000     391.800000     401.600000      88.000000   
75%        87.000000     426.800000     420.400000     135.000000   
max       240.000000     449.700000     448.300000     339.000000   

               month  
count  186552.000000  
mean        6.623606  
std         3.453293  
min         1.000000  
25%         4.000000  
50%         7.000000  
75%        10.000000  
max        12.000000

In [5]:
row_data.corr()

Unnamed: 0  Unnamed: 0.1        bs        id       day  \
Unnamed: 0      1.000000      1.000000  0.044812  0.997630 -0.016948   
Unnamed: 0.1    1.000000      1.000000  0.044812  0.997630 -0.016948   
bs              0.044812      0.044812  1.000000  0.049972 -0.056745   
id              0.997630      0.997630  0.049972  1.000000 -0.018130   
day            -0.016948     -0.016948 -0.056745 -0.018130  1.000000   
year           -0.016452     -0.016452 -0.046022 -0.017532  0.863390   
yday           -0.005149     -0.005149 -0.032905 -0.005625  0.489361   
wday            0.000244      0.000244  0.003115  0.000179  0.000864   
Tmin0          -0.002030     -0.002030 -0.552804 -0.000605  0.140809   
Tmean1         -0.017055     -0.017055 -0.549254 -0.016952  0.133324   
Tmean2         -0.016817     -0.016817 -0.539900 -0.016725  0.138171   
Tmax0          -0.029782     -0.029782 -0.492575 -0.030778  0.108414   
rainfall       -0.032268     -0.032268 -0.167088 -0.020546  0.084528   
x               0.340827      0.340827  0.037205  0.320483 -0.034300   
y               0.445214      0.445214  0.066129  0.440280 -0.004189   
h               0.128965      0.128965 -0.051552  0.130794 -0.018591   
AR_start        0.005864      0.005864  0.001675  0.007786 -0.022478   
month          -0.004992     -0.004992 -0.032486 -0.005500  0.482620   

                  year      yday      wday     Tmin0    Tmean1    Tmean2  \
Unnamed: 0   -0.016452 -0.005149  0.000244 -0.002030 -0.017055 -0.016817   
Unnamed: 0.1 -0.016452 -0.005149  0.000244 -0.002030 -0.017055 -0.016817   
bs           -0.046022 -0.032905  0.003115 -0.552804 -0.549254 -0.539900   
id           -0.017532 -0.005625  0.000179 -0.000605 -0.016952 -0.016725   
day           0.863390  0.489361  0.000864  0.140809  0.133324  0.138171   
year          1.000000 -0.017488 -0.001054 -0.010985 -0.013546 -0.015889   
yday         -0.017488  1.000000  0.003535  0.298029  0.287623  0.301279   
wday         -0.001054  0.003535  1.000000 -0.012141 -0.016456 -0.009252   
Tmin0        -0.010985  0.298029 -0.012141  1.000000  0.930147  0.886466   
Tmean1       -0.013546  0.287623 -0.016456  0.930147  1.000000  0.951105   
Tmean2       -0.015889  0.301279 -0.009252  0.886466  0.951105  1.000000   
Tmax0        -0.012815  0.236995  0.004681  0.865609  0.908863  0.871909   
rainfall     -0.008957  0.182993  0.014291  0.326822  0.314262  0.319959   
x            -0.033601 -0.009894  0.001935 -0.055318 -0.035377 -0.034894   
y            -0.005402  0.001036  0.001366  0.003813 -0.019563 -0.019803   
h            -0.017530 -0.006542  0.001696 -0.074610 -0.081165 -0.081081   
AR_start     -0.020310 -0.009439 -0.013737  0.010864  0.015508  0.013843   
month        -0.016316  0.984613 -0.005839  0.291236  0.278295  0.290770   

                 Tmax0  rainfall         x         y         h  AR_start  \
Unnamed: 0   -0.029782 -0.032268  0.340827  0.445214  0.128965  0.005864   
Unnamed: 0.1 -0.029782 -0.032268  0.340827  0.445214  0.128965  0.005864   
bs           -0.492575 -0.167088  0.037205  0.066129 -0.051552  0.001675   
id           -0.030778 -0.020546  0.320483  0.440280  0.130794  0.007786   
day           0.108414  0.084528 -0.034300 -0.004189 -0.018591 -0.022478   
year         -0.012815 -0.008957 -0.033601 -0.005402 -0.017530 -0.020310   
yday          0.236995  0.182993 -0.009894  0.001036 -0.006542 -0.009439   
wday          0.004681  0.014291  0.001935  0.001366  0.001696 -0.013737   
Tmin0         0.865609  0.326822 -0.055318  0.003813 -0.074610  0.010864   
Tmean1        0.908863  0.314262 -0.035377 -0.019563 -0.081165  0.015508   
Tmean2        0.871909  0.319959 -0.034894 -0.019803 -0.081081  0.013843   
Tmax0         1.000000  0.274831 -0.015492 -0.039360 -0.081217  0.016990   
rainfall      0.274831  1.000000 -0.128619  0.165800  0.221880  0.005803   
x            -0.015492 -0.128619  1.000000 -0.001812  0.304253 -0.002669   
y            -0.039360  0.165800 -0.001812  1.000000  0.1637

In [72]:
row_data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'bs', 'id', 'day', 'year', 'yday', 'wday',
       'Tmin0', 'Tmean1', 'Tmean2', 'Tmax0', 'rainfall', 'x', 'y', 'h', 'type',
       'AR_start', 'type1', 'month'],
      dtype='object')

In [93]:
data = pd.DataFrame(index=row_data.day, data=row_data[['bs', 'id', 'year', 'yday', 'wday',
       'Tmin0', 'Tmean1', 'Tmean2', 'Tmax0', 'rainfall', 'x', 'y', 'h', 'type',
       'AR_start', 'type1', 'month']])

In [94]:
data.head()

bs  id  year  yday  wday  Tmin0  Tmean1  Tmean2  Tmax0  rainfall  \
day                                                                           
575  5.236442  87  1963    43     2   -0.5    -0.5    -0.5    3.0        14   
576  5.123964  87  1963    44     3   -4.0     1.0    -0.5    3.5        14   
577  4.564348  87  1963    45     4   -2.5     0.0     1.0    2.5        14   
578  4.127134  87  1963    46     5    0.5     0.0     0.0    1.5        14   
579  3.850148  87  1963    47     6   -1.5     1.0     0.0    1.0        14   

         x      y   h  type  AR_start type1  month  
day                                                 
575  351.3  385.4  10  D2/E     False     D      2  
576  351.3  385.4  10  D2/E     False     D      2  
577  351.3  385.4  10  D2/E     False     D      2  
578  351.3  385.4  10  D2/E     False     D      2  
579  351.3  385.4  10  D2/E     False     D      2

In [95]:
print('max:', row_data.day.max(), ',min:',row_data.day.min())

max: 820 ,min: 91


In [165]:
data = row_data[['bs', 'id','day', 'Tmin0', 'rainfall', 'x', 'y', 'h']]

In [97]:
test = np.array(make3d(data))

dMin 91, dMax 820, num 2714


In [98]:
test.shape

(729, 2714)

In [160]:
def make3d(pd_data):
    dayMin = pd_data.day.min()
    dayMax = pd_data.day.max()
    stations = pd_data.id.unique()
    column_num = len(pd_data.columns)
    print('dMin {}, dMax {}, stations {}'.format(dayMin, dayMax, stations))
    
    result = []
    for day in range(dayMin, dayMax):
        mat = []
        data_on_day = pd_data[pd_data.day == day] # その日のデータのみ
        for stat_id in stations:
            # もし、あるstationのデータがあったら
            station_data = data_on_day[data_on_day.id == stat_id]
            if not station_data.empty:
                mat.append(list(station_data.as_matrix().reshape((8))))
            else:
                mat.append([0, 0, 0, 0, 0, 0, 0, 0])
        result.append(mat)
    return result

In [161]:
data[0:1].as_matrix().reshape((8))

array([   4.46590812,   82.        ,  575.        ,    6.        ,
         60.        ,  351.8       ,  382.3       ,   31.        ])

In [167]:
make3d(data)

dMin 91, dMax 820, stations [  82   87   88   89   97  101  102  103  104  107  109  110  112  114  115
  116  120  185  186  187  188  226  238  239  429  430  431  432  433  452
  453  454  458  459  460  492  493  612  613  615  618  620  621  624  630
  631  632  636  641  677  891  892  893  895  898  899  900  914  915  920
  922  925  928  929  930  934  938  940  942  961  962 1074 1096 1099 1190
 1210 1211 1212 1228 1230 1234 1239 1282 1377 1378 1379 1380 1381 1382 1383
 1384 1385 1386 1387 1393 1394 1397 1398 1399 1401 1402 1403 1404 1410 1411
 1412 1413 1415 1416 1417 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428
 1436 1438 1440 1441 1442 1443 1444 1445 1446 1447 1448 1450 1453 1454 1458
 1465 1466 1467 1468 1470 1471 1472 1474 1475 1476 1477 1478 1479 1486 1487
 1490 1491 1493 1494 1499 1500 1501 1502 1503 1504 1508 1511 1512 1513 1514
 1516 1517 1519 1523 1524 1535 1536 1539 1540 1545 1546 1555 1556 1559 1560
 1561 1564 1565 1571 1572 1582 1583 1584 1585 1592 1593 1594

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [54]:
data.head()

bs  day  Tmin0  rainfall      x      y   h
0  4.465908  575    6.0        60  351.8  382.3  31
1  3.891820  576    6.5        41  351.8  382.3  31
2  4.007333  577    4.5        41  351.8  382.3  31
3  4.110874  578    5.5        41  351.8  382.3  31
4  4.672829  579    2.0        41  351.8  382.3  31

In [86]:
data['id'].unique()

array([87, 82])

In [159]:
list(data[data.id == 82][data.day == 575].as_matrix().reshape((8)))

/home/admin/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


[4.4659081186545802,
 82.0,
 575.0,
 6.0,
 60.0,
 351.80000000000001,
 382.30000000000001,
 31.0]

In [125]:
np.array([]).push(np.array([]))

AttributeError: 'numpy.ndarray' object has no attribute 'push'

In [149]:
[]

[]

In [308]:
def to_tensor(pd_data):
    dayMin = pd_data.day.min()
    dayMax = pd_data.day.max()
    stations = pd_data.id.unique()
    column_num = len(pd_data.columns)
    
    result = np.empty((0, len(stations), 8), float)
    for day in range(dayMin, dayMax):
        mat = np.empty((0, 8), float)
        data_on_day = pd_data[pd_data.day == day] # その日のデータのみ
        for stat_id in stations:
            # もし、あるstationのデータがあったら
            station_data = data_on_day[data_on_day.id == stat_id]
            if not station_data.empty:
                mat = np.append(mat, station_data.as_matrix(), axis = 0)
            else:
                mat = np.append(mat, np.array([[0., 0., 0., 0., 0., 0., 0., 0.]]), axis = 0)
        result = np.append(result, mat.reshape(1, len(stations), 8), axis = 0)
    return result

array([[[   0.        ,    0.        ,    0.        , ...,    0.        ,
            0.        ,    0.        ],
        [   6.66057515,   87.        ,   91.        , ...,  351.3       ,
          385.4       ,   10.        ]],

       [[   0.        ,    0.        ,    0.        , ...,    0.        ,
            0.        ,    0.        ],
        [   7.05531284,   87.        ,   92.        , ...,  351.3       ,
          385.4       ,   10.        ]],

       [[   0.        ,    0.        ,    0.        , ...,    0.        ,
            0.        ,    0.        ],
        [   7.6912001 ,   87.        ,   93.        , ...,  351.3       ,
          385.4       ,   10.        ]],

       ..., 
       [[   3.8918203 ,   82.        ,  817.        , ...,  351.8       ,
          382.3       ,   31.        ],
        [   0.        ,    0.        ,    0.        , ...,    0.        ,
            0.        ,    0.        ]],

       [[   3.8918203 ,   82.        ,  818.        , ...,  351.8  

In [218]:
data[:10].as_matrix()

array([[   4.46590812,   82.        ,  575.        ,    6.        ,
          60.        ,  351.8       ,  382.3       ,   31.        ],
       [   3.8918203 ,   82.        ,  576.        ,    6.5       ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   4.00733319,   82.        ,  577.        ,    4.5       ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   4.11087386,   82.        ,  578.        ,    5.5       ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   4.67282883,   82.        ,  579.        ,    2.        ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   4.09434456,   82.        ,  580.        ,    4.5       ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   4.09434456,   82.        ,  581.        ,    2.5       ,
          41.        ,  351.8       ,  382.3       ,   31.        ],
       [   3.78418963,   82.        ,  58

In [255]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(np.concatenate([a1, a2], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [269]:
np.array([[]]).shape

(1, 0)